<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
        <groupId>com.github.maxbechtold</groupId>
        <artifactId>fast-approval</artifactId>
        <version>0.6.1-SNAPSHOT</version>
  </parent>
  <artifactId>approval-sesame</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>
  <dependencies>
      <dependency>
        <groupId>org.eclipse.rdf4j</groupId>
        <artifactId>rdf4j-model</artifactId>
        <version>3.7.4</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.rdf4j</groupId>
        <artifactId>rdf4j-rio-turtle</artifactId>
        <version>3.7.4</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.rdf4j</groupId>
        <artifactId>rdf4j-rio-api</artifactId>
        <version>3.7.4</version>
      </dependency>
      <dependency>
          <groupId>${project.groupId}</groupId>
          <artifactId>approval-core</artifactId>
          <version>${project.version}</version>
      </dependency>
  </dependencies>
</project>
